apiVersion : apps/v1
kind: Deployment
metadata:
  name: "myaks2cluster-da87"
spec:
  replicas: 2
  selector:
    matchLabels:
      app: "myaks2cluster-da87"
  template:
    metadata:
      labels:
        app: "myaks2cluster-da87"
    spec:
      containers:
        - name: "myaks2cluster-da87"
          image: "myacr20225.azurecr.io/myaks2cluster"
          ports:
          - containerPort: 8123